name: ci
on: push
jobs:
  # FIXME: Uncomment once there are unit tests
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #     - run: yarn install --frozen-lockfile
  #     - run: yarn run build
  #     - run: yarn run test --all --ci --coverage
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run lint
